from enum import Enum


class EventType(Enum):
    """
    Enum class for event types.
    """
    GAME_ENDED = "GAME_ENDED"
    GAME_STARTED = "GAME_STARTED"
    PLAYER_JOINED = "PLAYER_JOINED"
    TEAM_REJECTED = "TEAM_REJECTED"
    ROUND_COMPLETED = "ROUND_COMPLETED"
    QUEST_COMPLETED = "QUEST_COMPLETED"
    TEAM_PROPOSAL_SUBMITTED = "TEAM_PROPOSAL_SUBMITTED"
    ROUND_VOTE_CAST = "ROUND_VOTE_CAST"
    QUEST_VOTING_STARTED = "QUEST_VOTING_STARTED"
    QUEST_VOTE_REQUESTED = "QUEST_VOTE_REQUESTED"
    QUEST_VOTE_CAST = "QUEST_VOTE_CAST"
    ASSASSINATION_STARTED = "ASSASSINATION_TARGET_STARTED"
    ASSASSINATION_TARGET_REQUESTED = "ASSASSINATION_TARGET_REQUESTED"
    ASSASSINATION_TARGET_SUBMITTED = "ASSASSINATION_TARGET_SUBMITTED"
    ASSASSINATION_FAILED = "ASSASSINATION_FAILED"
    ASSASSINATION_SUCCEEDED = "ASSASSINATION_SUCCEEDED"

    QUEST_STARTED = "QUEST_STARTED"
    ROUND_STARTED = "ROUND_STARTED"
    SELECT_TEAM = "SELECT_TEAM"
